[package]
name = "generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemafy_lib = "0.5"
serde = "1"
serde_json = "1"
quote="1"
derive_more = "0.99"
